name: react-demo-tests
on:
  push:
    branches: [master]
    paths:
      - exercises/react-demo/**
      - package.json
      - .github/workflows/react-tests.yml
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    container: cypress/included:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies 📦
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          start: npm run dev -- --filter react-demo
          wait-on: http://127.0.0.1:5173
      - name: Run Tests 🧪
        run: npm run test -- --filter react-demo 