name: react-tests
on:
  push:
    branches: [master]
    paths:
      - "exercises/react-demo/**"
      - package.json
      - .github/workflows/react-tests.yml

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - name: Install 📦
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - name: Run Tests 🧪
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./exercises/react-demo
          install: false
          start: npm run dev
          wait-on: http://127.0.0.1:5500
